config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get '/confirmation' => 'sections#confirmation', as: 'confirm'
  resources :users, except: [:destroy]

  namespace :admin do
    get '/login' => 'sessions#new'
    post 'admin/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    resources :users, only: [:index]
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :password, presence: true, length: { minimum: 6 },
    confirmation: true, on: :create
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  before_save { self.email = email.downcase }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :coda, presence: true, length: { maximum: 10  }, uniqueness: true,
    format: { with: (/[a+l]+[0-9]{8}/) }

  def self.to_csv(users = {})
    CSV.generate(users) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  before_action :already_on, except: [:destroy]
  def new
  end

  def create
    admin = Admin.find_by_email(params[:email])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      flash[:notice] = "Bienvenido #{admin.first_name}"
      redirect_to admin_users_path
    else
      flash[:error] = "Email o contraseña incorrecta."
      redirect_to admin_login_path
    end
  end

  def destroy
    session[:admin_id] = nil
    flash[:notice] = "Sesión terminada exitosamente."
    redirect_to admin_login_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_auth

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :admin_auth, :already_on

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  def already_on
    redirect_to admin_users_path if current_admin
  end

  def admin_auth
    redirect_to admin_login_path unless current_admin
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def confirmation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  helper_method :talleres
  def new
    @user = User.new
    talleres
  end
  def create
    @user = User.new(permited_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      flash[:notice] = "Te has registrado con éxito"
      redirect_to confirm_path
    else
      respond_with @user
    end
  end

  private
  def permited_params
    params.require(:user).permit(:first_name, :last_name, :coda, :workshop)
  end

  def talleres
    @talleres = [ "Festo", "CEBETI", "CARPLASTIC", "AGENCIA ESPACIAL MEXICANA" ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<%= link_to "Cerrar Sesión", admin_logout_path, class: 'btn btn-primary' %>

<p>
  Descargar:
  <%= link_to "Excel", admin_users_path(format: "csv") %> |
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre(s)</th>
      <th>Apellidos</th>
      <th>Matrícula</th>
      <th>Taller</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.coda %></td>
        <td><%= user.workshop %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<div class="logos row">
  <%= image_tag('TECMIlogo.png', height: 'auto', width: '350', class: "logo") %>
  <%= image_tag('IEEElogo.png', height: 'auto', width: '350', class: "logo") %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ieeemilenio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ieeemilenio" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/sections/confirmation.html.erb
<div class="confirmation">
  <h1>¡Gracias por registrarse!</h1>
  <p>
    A continuación recibirá un correo electrónico a su correo institucional.
  </p>
</div>

app/views/users/new.html.erb
<div class="user-form">
  <h1>Forma de registro</h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name, label: "Nombre(s)" %>
    <%= f.input :last_name, label: "Apellido(s)" %>
    <%= f.input :coda, label: "Matrícula", hint: "Formato: al00000000" %>
    <%= f.input :workshop, label: "Taller", collection: @talleres,
            as: :select, group_method: :talleres, hint: "Selecciona un taller si asistirás a uno (Cupo limitado a 25 personas)" %>
    <%= f.submit "Registrarme", class: "btn btn-primary" %>
  <% end %>
</div>